version: '3.9'

services:
  web:
    build: .
    container_name: budget_web
    command: gunicorn budget_management.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped

  celery:
    build: .
    container_name: budget_celery_worker
    command: celery -A budget_management worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: budget_celery_beat
    command: celery -A budget_management beat --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: budget_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
