from django.contrib import admin
from .models import Brand, Campaign, SpendLog, DaypartingSchedule

class BrandAdmin(admin.ModelAdmin[Brand]): ...
class CampaignAdmin(admin.ModelAdmin[Campaign]): ...
class SpendLogAdmin(admin.ModelAdmin[SpendLog]): ...
class DaypartingScheduleAdmin(admin.ModelAdmin[DaypartingSchedule]): ...
